SSCMS/SSCMS/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import home

urlpatterns = [
    path('', home, name="login"),
    path('user/', include("user.urls")),
    path('course/', include("course.urls")),
]

SSCMS/course/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from .cbvs import ScoreUpdateView, RateUpdateView, StudentCourseDetailView

urlpatterns = [
    path('', to_home, name="course"),
    path('<slug:kind>/', home, name="course"),
    path('teacher/create_course', create_course, name="create_course"),
    path('teacher/view_detail/<int:course_id>', view_detail, name="view_detail"),
    path('teacher/create_schedule/<int:course_id>', create_schedule, name="create_schedule"),
    path('teacher/delete_schedule/<int:schedule_id>', delete_schedule, name="delete_schedule"),
    path('teacher/score/<int:pk>', ScoreUpdateView.as_view(), name="score"),
    path('teacher/handle_course/<int:course_id>/<int:handle_kind>', handle_course, name="handle_course"),

    path('student/view/<slug:view_kind>', view_course, name="view_course"),
    path('student/operate/<int:course_id>/<slug:operate_kind>', operate_course, name="operate_course"),

    path('student/evaluate/<int:pk>', RateUpdateView.as_view(), name="evaluate"),
    path('student/view_detail/<int:pk>', StudentCourseDetailView.as_view(), name="sview_detail"),
]

SSCMS/user/urls.py
from user import views
from django.urls import path

urlpatterns = [
    path('login/', views.home, name="login"),
    path('login/<slug:kind>', views.login, name="login"),
    path('register/<slug:kind>', views.register, name="register"),
    path('update/<slug:kind>', views.update, name="update"),
    path('logout', views.logout, name="logout")
]

SSCMS/course/models.py
from django.db import models
import datetime
from user.models import Student, Teacher
from constants import COURSE_STATUS, COURSE_OPERATION


def current_year():
    return datetime.date.today().year


class Course(models.Model):
    credits = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]

    semesters = [
        ('Autumn', "Fall"),
        ('Spring', "Spring")
    ]

    name = models.CharField(max_length=50, verbose_name="Course name")
    introduction = models.CharField(max_length=250, verbose_name="Introduction")
    credit = models.IntegerField(verbose_name="Credits")
    max_number = models.IntegerField(verbose_name="Max enrollment")
    year = models.IntegerField(verbose_name="Year", default=current_year)
    semester = models.CharField(max_length=20, verbose_name="Semester", choices=semesters)
    status = models.IntegerField(verbose_name="Course status", default=1)
    teacher = models.ForeignKey(Teacher, verbose_name="Course instructor", on_delete=models.CASCADE)

    def get_status_text(self):
        return COURSE_STATUS[self.status]

    def get_op_text(self):
        return COURSE_OPERATION[self.status]

    def get_current_count(self):
        courses = StudentCourse.objects.filter(course=self, with_draw=False)
        return len(courses)

    def get_schedules(self):
        schedules = Schedule.objects.filter(course=self)
        return schedules

    def __str__(self):
        return "%s (%s)" % (self.name, self.teacher.name)


def weekday_choices():
    weekday = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    return [(i + 1, weekday[i]) for i in range(7)]


class Schedule(models.Model):
    weekday = models.IntegerField(choices=weekday_choices(), verbose_name="Date")
    start_time = models.TimeField(verbose_name="Course begin at")
    end_time = models.TimeField(verbose_name="Course end at")
    location = models.CharField(max_length=100, verbose_name="Course location")
    remarks = models.CharField(max_length=100, verbose_name="Note", null=True, blank=True)

    start_week = models.IntegerField(verbose_name="Starting week")
    end_week = models.IntegerField(verbose_name="Ending week")

    intervals = [
        (1, "Once every week"),
        (2, "Once every two weeks")
    ]
    week_interval = models.IntegerField(verbose_name="Week intervals", choices=intervals, default=1)

    course = models.ForeignKey(Course, verbose_name="Course name", on_delete=models.CASCADE)

    def __str__(self):
        s = "From week %s to week %s " % (self.start_week, self.end_week)
        if self.week_interval == 2:
            s += "(once every two weeks) "
        s += "on %s %s-%s " % (self.get_weekday_display(), self.start_time.strftime("%H:%M"),
                            self.end_time.strftime("%H:%M"))
        s += "at %s" % self.location
        if self.remarks:
            s += " (Note: %s)" % self.remarks
        return s


class StudentCourse(models.Model):
    create_time = models.DateTimeField(auto_now=True)
    with_draw = models.BooleanField(default=False)
    with_draw_time = models.DateTimeField(default=None, null=True)
    scores = models.IntegerField(verbose_name="Score", null=True)
    comments = models.CharField(max_length=250, verbose_name="Instructor's comment", null=True)

    rates = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]

    rating = models.IntegerField(verbose_name="Student's rating", choices=rates, null=True,
                                 help_text="5 being the highest, 1 being the lowest.")
    assessment = models.CharField(max_length=250, verbose_name="Student's comment", null=True)

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

SSCMS/course/forms.py
from django import forms
from .models import Course, Schedule, StudentCourse


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        exclude = ['status', 'teacher']


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        exclude = ["course"]


class ScoreForm(forms.ModelForm):
    class Meta:
        model = StudentCourse
        fields = ["student", "course", "scores", "comments"]

    student = forms.CharField(label="student", disabled=True)
    course = forms.CharField(label="course", disabled=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['student'] = self.instance.student
        self.initial['course'] = self.instance.course

    def clean_student(self):
        return self.initial['student']

    def clean_course(self):
        return self.initial['course']


class RateForm(forms.ModelForm):
    class Meta:
        model = StudentCourse
        fields = ["course", "scores", "comments", "rating", "assessment"]

    course = forms.CharField(label="Course", disabled=True)
    scores = forms.IntegerField(label="Score", disabled=True)
    comments = forms.CharField(label="Instructor's evaluation", disabled=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['course'] = self.instance.course
        self.initial['scores'] = self.instance.scores
        self.initial['comments'] = self.instance.comments

    def clean_course(self):
        return self.initial['course']

    def clean_scores(self):
        return self.initial['scores']

    def clean_comments(self):
        return self.initial['comments']

SSCMS/course/views.py
from django.shortcuts import render, redirect, reverse
from django.http.response import HttpResponse
from django.db.models import Q
from django.utils import timezone

from user.util import get_user
from .models import Course, StudentCourse, Schedule
from constants import INVALID_KIND, INVALID_REQUEST_METHOD, COURSE_FULL
from .forms import CourseForm, ScheduleForm


def to_home(request):
    kind = request.session.get('kind', '')
    return redirect(reverse("course", kwargs={"kind": kind}))


def home(request, kind):
    if kind == "student":
        return student_home(request)
    elif kind == "teacher":
        return teacher_home(request)
    else:
        return HttpResponse(INVALID_KIND)


def student_home(request):
    return redirect(reverse("view_course", kwargs={"view_kind": "current"}))


def teacher_home(request):
    user = get_user(request, 'teacher')

    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        'name': user.name,
        'kind': 'teacher'
    }

    is_search = False
    search_key = ""
    if request.method == "POST":
        search_key = request.POST.get("search")
        if search_key:
            is_search = True

    context = {
        'info': info
    }

    q = Q(teacher=user)
    if is_search:
        q = q & Q(name__icontains=search_key)
        context["search_key"] = search_key

    context["course_list"] = Course.objects.filter(q).order_by('status')

    return render(request, 'course/teacher/home.html', context)


def create_course(request):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.status = 1
            obj.teacher = user

            obj.save()
            return redirect(reverse("course", kwargs={"kind": "teacher"}))
    elif request.method == 'GET':
        form = CourseForm()
    else:
        return HttpResponse(INVALID_REQUEST_METHOD)

    return render(request, 'course/teacher/create_course.html', {'info': info, 'form': form})


def create_schedule(request, course_id):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    course = Course.objects.get(pk=course_id)

    if request.method == 'POST':
        form = ScheduleForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.course = course
            obj.save()

            return redirect(reverse("view_detail", kwargs={"course_id": course_id}))
    elif request.method == 'GET':
        form = ScheduleForm()
    else:
        return HttpResponse(INVALID_REQUEST_METHOD)

    return render(request, 'course/teacher/create_schedule.html', {'info': info, 'form': form, "course": course})


def delete_schedule(request, schedule_id):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    schedule = Schedule.objects.get(pk=schedule_id)

    course_id = request.GET.get("course_id") or schedule.course.id

    schedule.delete()

    return redirect(reverse("view_detail", kwargs={"course_id": course_id}))


def handle_course(request, course_id, handle_kind):
    """
    :param request:
    :param course_id:
    :param handle_kind:
            1: "Start selection",
            2: "End selection",
            3: "End course",
            4: "Grade"
    :return:
    """
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    course = Course.objects.get(pk=course_id)
    if course.status == handle_kind and course.status < 5:
        if course.status == 4:
            scs = StudentCourse.objects.filter(Q(course=course) & Q(with_draw = False))
            all_given = True
            res = ""
            for sc in scs:
                if sc.scores is None:
                    all_given = False
                    res += "<div>%s has not been graded</div>" % sc.student

            if all_given:
                course.status += 1
                course.save()
                return redirect(reverse("view_detail", kwargs={"course_id": course.id}))
            else:
                return HttpResponse(res)
        else:
            course.status += 1
            course.save()

    course_list = Course.objects.filter(teacher=user)
    return render(request, 'course/teacher/home.html', {'info': info, 'course_list': course_list})


def view_detail(request, course_id):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    course = Course.objects.get(pk=course_id)
    c_stu_list = StudentCourse.objects.filter(Q(course=course) & Q(with_draw = False))
    sche_list = Schedule.objects.filter(course=course)

    context = {
        "info": info,
        "course": course,
        "course_students": c_stu_list,
        "schedules": sche_list
    }

    if course.status == 5:
        sorted_cs_list = sorted(c_stu_list, key=lambda cs: cs.scores)
        context["sorted_course_students"] = sorted_cs_list

    return render(request, "course/teacher/course.html", context)


def view_course(request, view_kind):
    """
    :param view_kind:
        current: Check current courses
        is_end: Check ended courses
        select: Select courses
        withdraw: Drop courses
    """
    user = get_user(request, "student")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "student"}))

    is_search = False
    search_key = ""
    if request.method == "POST":
        search_key = request.POST.get("search")
        if search_key:
            is_search = True

    info = {
        "name": user.name,
        "kind": "student",
    }

    course_list = []

    if view_kind in ["select", "current", "withdraw", "is_end"]:
        if view_kind == "select":
            q = Q(status=2)
            if is_search:
                q = q & (Q(name__icontains=search_key) | Q(teacher__name__icontains=search_key))

            course_list = Course.objects.filter(q)

            my_course = StudentCourse.objects.filter(Q(student=user) & Q(with_draw=False))
            my_cids = [c.course.id for c in my_course]
            course_list = [c for c in course_list if c.id not in my_cids]
        else:
            q = Q(student=user) & Q(with_draw=False)
            if is_search:
                q = q & (Q(course__name__icontains=search_key) | Q(course__teacher__name__icontains=search_key))
            my_course = StudentCourse.objects.filter(q)
            if view_kind == "current":
                course_list = [c.course for c in my_course if c.course.status < 4]
            elif view_kind == "withdraw":
                course_list = [c.course for c in my_course if c.course.status == 2]
            elif view_kind == "is_end":
                course_list = [c for c in my_course if c.course.status >= 4]

    else:
        return HttpResponse(INVALID_REQUEST_METHOD)

    context = {
        'info': info,
        'view_kind': view_kind,
        'course_list': course_list
    }
    if is_search:
        context["search_key"] = search_key

    return render(request, 'course/student/home.html', context)


def operate_course(request, operate_kind, course_id):
    """
    :param operate_kind:
        current: Check current courses
        is_end: Check ended courses
        select: Select courses
        withdraw: Drop courses
    """
    user = get_user(request, "student")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "student"}))

    if operate_kind == "select":
        course = Course.objects.filter(pk=course_id).get()
        if course.get_current_count() >= course.max_number:
            return HttpResponse(COURSE_FULL)
        else:
            new_course = StudentCourse(student=user, course=course)
            new_course.save()
    elif operate_kind == "withdraw":
        q = Q(course__id=course_id) & Q(student=user) & Q(with_draw=False)
        course = StudentCourse.objects.filter(q).get()
        course.with_draw = True
        course.with_draw_time = timezone.now()
        course.save()
    else:
        return HttpResponse(ILLEGAL_KIND)
    return redirect(reverse("view_course", kwargs={"view_kind": operate_kind}))

SSCMS/templates/course/teacher/course.html
{% extends "course/nav.html" %}
{% block title %}Course info{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
    <h3>Course info<input class="button right-button" type="button" value="Return home"
                   onclick='location.href="{% url 'course' 'teacher'%}"'/></h3>
    <table class="item-list detail-list">
        <thead>
            <tr>
                <th>Course id</th>
                <th>Course name</th>
                <th>Credits</th>
                <th>Current enrollment/Max enrollment</th>
                <th>Year</th>
                <th>Semester</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ course.id }}</td>
                <td>{{ course.name }}</td>
                <td>{{ course.credit }}</td>
                <td>{{ course.get_current_count }}/{{ course.max_number }}</td>
                <td>{{ course.year }}</td>
                <td>{{ course.get_semester_display }}</td>
            </tr>
        </tbody>
    </table>

    <h3>Course schedule<input class="button right-button" type="button" value="Add schedule" onclick='location.href="{% url 'create_schedule' course.id%}"'/></h3>
    <table class="item-list schedule-list">
        <thead>
            <tr>
                <th class="schedule-no">Version</th>
                <th class="schedule-no">Detail</th>
                <th class="schedule-no">Operation</th>
            </tr>
        </thead>
        <tbody>
            {% for schedule in schedules %}
            <tr>
                <td>{{ schedule.id }}</td>
                <td>{{ schedule }}</td>
                <td>
                    <input class="button" type="button" value="Delete"
                           onclick='location.href="{% url 'delete_schedule' schedule.id%}?course_id={{ course.id }}"'/>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Student list
        {% if course.status == 4 %}
            <input class="button right-button" type="button" value="Finish grading" onclick='location.href="{% url 'handle_course' course.id 4%}"' />
        {% endif %}
    </h3>
    <table class="item-list student-list">
        <thead>
            <tr>
                <th class="student-no">Student id</th>
                <th class="student-name">Student name</th>
                <th class="student-email">Student email</th>
                <th class="student-score">Score</th>
                <th class="student-comments">Comment</th>
                <th class="operation">Operation</th>
            </tr>
        </thead>
        <tbody>
            {% for cs in course_students %}
            <tr>
                <td>{{ cs.student.get_id}}</td>
                <td>{{ cs.student.name }}</td>
                <td>{{ cs.student.email }}</td>
                <td>
                    {% if cs.scores == None %}-{% endif %}
                    {% if cs.scores != None %}{{ cs.scores }}{% endif %}
                </td>
                <td>
                    {% if cs.scores == None %}-{% endif %}
                    {% if cs.scores != None %}{{ cs.comments }}{% endif %}
                </td>
                <td class="operation">
                    {% if course.status == 4 %}
                        {% if cs.scores == None %}
                            <input class="button right-button" type="button" value="Grade"
                               onclick='location.href="{% url 'score' cs.id%}"' />
                        {% else %}
                            <input class="button right-button" type="button" value="Modify score"
                               onclick='location.href="{% url 'score' cs.id%}?update=1"' />
                        {% endif %}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if course.status == 5 %}
    <h3>Student's comment</h3>
    <table class="item-list student-list">
        <thead>
            <tr>
                <th class="student-score">Student's rating</th>
                <th class="student-comments">Student's comment</th>
            </tr>
        </thead>
        <tbody>
            {% for cs in sorted_course_students %}
            {% if cs.rating != None %}
            <tr>
                <td>{{ cs.rating }}</td>
                <td>{{ cs.assessment }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock %}

SSCMS/templates/course/teacher/create_course.html
{% extends "course/nav.html" %}
{% block title %}Create course{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/form.css' %}" rel="stylesheet">
    <h3>Create Course</h3>
    <div class="form create-update-from">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div class="submit-button">
                <input type="submit" value="Create"/>
                <input type="button" value="Return"  onclick='location.href="{% url 'course' "teacher"%}"' />
            </div>
        </form>
    </div>
{% endblock %}

SSCMS/templates/course/teacher/create_schedule.html
{% extends "course/nav.html" %}
{% block title %}Create schedule{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/form.css' %}" rel="stylesheet">
    <h3>Create schedule:&nbsp;&nbsp;&nbsp;&nbsp; {{ course.name }}</h3>
    <div class="form create-update-from">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div class="submit-button">
                <input type="submit" value="Create"/>
                <input type="button" value="Return"  onclick='location.href="{% url 'view_detail' course.id%}"'/>
            </div>
        </form>
    </div>
{% endblock %}

SSCMS/templates/course/teacher/home.html
{% extends "course/nav.html" %}
{% block title %}HomePage{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
    <div class="main-container">
        <div class="main-bar">
            <form class="search-form" method="post">
                {% csrf_token %}
                <input class="input" id="search-key" type="text" name="search" {% if search_key != None %} value="{{ search_key }}" {% endif %}/>
                <input class="button" type="submit" value="Search" />
            </form>

            <input class="button right-button" type="button" value="Create courses"  onclick='location.href="{% url 'create_course' %}"' />
        </div>
        <table class="item-list course-list">
            <thead>
                <tr>
                    <th class="course-no">Course id</th>
                    <th class="course-name">Course name</th>
                    <th class="course-credit">Credits</th>
                    <th class="course-number">Current enrollment<br>/Max enrollment</th>
                    <th class="course-year">Year</th>
                    <th class="course-semester">Semester</th>
                    <th class="course-status">Status</th>
                    <th class="course-operation">Operations</th>
                </tr>
            </thead>
            <tbody>
                {% for course in course_list %}
                    <tr id="course-id-{{ course.id }}">
                    <td class="course-no">{{ course.id }}</td>
                    <td class="course-name">{{ course.name }}</td>
                    <td class="course-credit">{{ course.credit }}</td>
                    <td class="course-number">{{ course.get_current_count }}/{{ course.max_number }}</td>
                    <td class="course-year">{{ course.year }}</td>
                    <td class="course-semester">{{ course.get_semester_display }}</td>
                    <td class="course-status">{{ course.get_status_text }}</td>
                    <td class="course-operation">
                        {% if course.status < 4 %}
                            <input class="button right-button" type="button" value="{{ course.get_op_text }}"
                              onclick='location.href="{% url 'handle_course' course.id course.status %}"' />
                        {% endif %}
                        {% if course.status == 4 %}
                        {# Grading after course ended #}
                            <input class="button right-button" type="button" value="{{ course.get_op_text }}"
                                   onclick='location.href="{% url 'view_detail' course.id %}"' />
                        {% else %}
                            <input class="button right-button" type="button" value="Details"
                                   onclick='location.href="{% url 'view_detail' course.id %}"' />
                        {% endif %}
                    </td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock %}

SSCMS/templates/course/teacher/score.html
{% extends "course/nav.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/form.css' %}" rel="stylesheet">
    <h3>{{ title }}</h3>
    <div class="form create-update-from">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div class="submit-button">
                <input type="submit" value="Confirm"/>
                <input type="button" value="Cancel"  onclick='location.href="{{ return_url }}"' />
            </div>
        </form>
    </div>
{% endblock %}